/* Functional connections: live Morning Brief + published calendar feed */
(function(){
  data.connections=data.connections||{calendarUrl:'',calendarLastSync:'',briefingLastSync:'',calendarEvents:[]};
  data.liveBriefing=data.liveBriefing||{updatedAt:'',topics:[]};
  const originalHome=homePage,originalCalendar=calendarPage,originalSettings=settingsPage,originalBriefing=briefingPage,originalRender=render;
  tabs.forEach(t=>{if(t[0]==='command'){t[1]='Command';t[3]='Command'}if(t[0]==='briefing'){t[1]='Morning Brief';t[3]='Morning Brief'}});
  window.upcoming=function(){return[...data.events,...(data.connections.calendarEvents||[])].sort((a,b)=>(a.date+(a.start||'')).localeCompare(b.date+(b.start||''))).slice(0,8)};
  function safeUrl(url){return/^https?:\/\//i.test(url)?url:'#'}
  function storyCards(){const live=data.liveBriefing?.topics||[],topics=live.length?live:data.morningTopics.map((t,i)=>({...t,id:`local-${i}`,items:[]}));return`${section('Morning Brief','Live headlines across your eight briefing topics')}<div class="connection-toolbar"><div><span class="live-dot ${live.length?'on':''}"></span><b>${live.length?'Live briefing connected':'Using local briefing copy'}</b><small>${data.liveBriefing.updatedAt?`Updated ${new Date(data.liveBriefing.updatedAt).toLocaleString()}`:'Refresh to load current headlines'}</small></div><button class="btn gold" onclick="refreshMorningBrief()">↻ Refresh Morning Brief</button></div><div class="grid live-topic-grid">${topics.map((topic,i)=>{const fallback=data.morningTopics[i]||{},items=topic.items||[];return`<section class="card live-topic"><div class="topic-header"><span class="topic-icon">${esc(fallback.icon||'•')}</span><div><b>${esc(topic.title||fallback.title)}</b><small>${esc(fallback.priority||'Latest developments')}</small></div></div>${items.length?items.slice(0,3).map((item,n)=>`<a class="live-story" href="${safeUrl(item.link)}" target="_blank" rel="noopener"><span>${n+1}</span><div><b>${esc(item.title)}</b><small>${esc(item.source||'News source')}${item.published?` • ${new Date(item.published).toLocaleDateString()}`:''}</small></div></a>`).join(''):`<h3>${esc(fallback.headline||'Morning update')}</h3><p>${esc(fallback.summary||'No live stories available yet.')}</p>`}<div class="topic-impact"><strong>WHY IT MATTERS</strong>${esc(fallback.impact||'Review the development and any practical implications.')}</div></section>`}).join('')}</div>`}
  function terminology(html){return html.replaceAll('Morning Briefing','Morning Brief').replaceAll('TOP PRIORITY','MISSION').replaceAll("TODAY'S FOCUS",'FOCUS MODE').replaceAll('Day Style','Focus Mode').replace('<h3>Quick Links</h3><span>Common actions</span>','<h3>Quick Actions</h3><span>Execute</span>')}
  window.homePage=function(){let html=terminology(originalHome()),start=html.indexOf('<div class="section"><h2>Morning Brief</h2>'),noteStart=start>=0?html.indexOf('<div class="brief-source-note">',start):-1;if(noteStart>=0){const noteEnd=html.indexOf('</div>',noteStart)+6;html=html.slice(0,start)+storyCards()+html.slice(noteEnd)}return`<div class="home-status-row"><button class="status-tile" onclick="refreshMorningBrief()"><span class="live-dot ${data.liveBriefing.topics?.length?'on':''}"></span><b>Morning Brief</b><small>${data.liveBriefing.topics?.length?'Connected':'Tap to connect'}</small></button><button class="status-tile" onclick="showPage('calendar')"><span class="live-dot ${data.connections.calendarUrl?'on':''}"></span><b>Apple Calendar</b><small>${data.connections.calendarUrl?'Feed connected':'Add published feed'}</small></button><button class="status-tile" onclick="showPage('command')"><span class="status-number">${data.priorities.filter(x=>!x.done).length}</span><b>Open Priorities</b><small>Command</small></button><button class="status-tile" onclick="showPage('heart')"><span class="status-number">${score()}</span><b>Readiness</b><small>${statusFor(score())}</small></button></div>${html}`};
  window.calendarPage=function(){return terminology(originalCalendar())+`${section('Calendar Connection','Read-only Apple Calendar feed')}<div class="grid two"><section class="card connection-card"><div class="card-title"><h3>Connect Published Calendar</h3><span>${data.connections.calendarUrl?'Connected':'Not connected'}</span></div><p class="copy">Paste a published Apple Calendar <b>webcal://</b> or <b>https://</b> subscription link. Events will appear in Today’s Schedule alongside locally created events.</p><label class="connection-label">Published calendar URL<input id="calendarFeedUrl" value="${esc(data.connections.calendarUrl||'')}" placeholder="webcal://pXX-caldav.icloud.com/published/2/..."></label><div class="connection-actions"><button class="btn gold" onclick="saveCalendarConnection()">Save & Sync</button><button class="btn" onclick="syncCalendar()">Sync Now</button><button class="btn danger" onclick="disconnectCalendar()">Disconnect</button></div><div class="notice">${data.connections.calendarLastSync?`Last synced ${new Date(data.connections.calendarLastSync).toLocaleString()} • ${(data.connections.calendarEvents||[]).length} events loaded`:'Publish a calendar in Apple Calendar, then paste its subscription URL here.'}</div></section><section class="card"><div class="card-title"><h3>Connected Events</h3><span>${(data.connections.calendarEvents||[]).length} imported</span></div><div class="list">${(data.connections.calendarEvents||[]).slice(0,8).map(e=>`<div class="list-row"><div><b>${esc(e.title)}</b><span>${esc(e.date)} • ${esc(toDisplayTime(e.start))}${e.location?` • ${esc(e.location)}`:''}</span></div><span class="tag">APPLE</span></div>`).join('')||'<div class="empty">No connected events yet.</div>'}</div></section></div>`};
  window.settingsPage=function(){return terminology(originalSettings())+`${section('Connections','Live services')}<div class="grid two"><section class="card"><div class="card-title"><h3>Morning Brief</h3><span>${data.liveBriefing.topics?.length?'Connected':'Ready'}</span></div><p class="copy">Uses a Vercel serverless feed to load current headlines for all eight briefing categories.</p><button class="btn gold" onclick="refreshMorningBrief()">Refresh Brief</button></section><section class="card"><div class="card-title"><h3>Apple Calendar</h3><span>${data.connections.calendarUrl?'Connected':'Optional'}</span></div><p class="copy">Connect a published, read-only Apple Calendar subscription feed from the Calendar page.</p><button class="btn" onclick="showPage('calendar')">Open Calendar Connection</button></section></div>`};
  window.briefingPage=function(){return terminology(originalBriefing()).replace('The dashboard currently stores briefing copy locally. A later connected-data phase can populate these sections automatically from your scheduled briefing.','Live headlines now populate the Home screen through the Morning Brief connection. The editor remains available for fallback copy and your “Why it matters” notes.')};
  renders.home=window.homePage;renders.calendar=window.calendarPage;renders.settings=window.settingsPage;renders.briefing=window.briefingPage;
  window.render=function(active='home'){originalRender(active);applyBranding()};
  function applyBranding(){document.title='Holleman Command Center — Morning Brief';const brand=document.querySelector('.brand small');if(brand)brand.textContent='COMMAND CENTER';const focus=document.querySelector('.focus-card small');if(focus)focus.textContent='FOCUS MODE';const top=document.querySelector('.status-chip:nth-child(2)');if(top)top.childNodes[0].nodeValue='FOCUS MODE'}
  window.refreshMorningBrief=async function(silent=false){if(!silent)toast('Refreshing Morning Brief…');try{const r=await fetch('/api/briefing',{headers:{accept:'application/json'}}),payload=await r.json();if(!r.ok)throw new Error(payload.error||'Unable to refresh briefing');data.liveBriefing={updatedAt:payload.updatedAt,topics:payload.topics||[]};data.connections.briefingLastSync=payload.updatedAt;saveData(false);refresh();if(!silent)toast('Morning Brief updated.')}catch(error){if(!silent)toast(error.message||'Morning Brief refresh failed.')}};
  window.saveCalendarConnection=function(){const input=document.getElementById('calendarFeedUrl');data.connections.calendarUrl=(input?.value||'').trim();saveData(false);syncCalendar()};
  window.syncCalendar=async function(silent=false){const url=data.connections.calendarUrl;if(!url){if(!silent)toast('Add a published calendar URL first.');return}if(!silent)toast('Syncing Apple Calendar…');try{const r=await fetch(`/api/calendar?url=${encodeURIComponent(url)}`,{headers:{accept:'application/json'}}),payload=await r.json();if(!r.ok)throw new Error(payload.error||'Unable to sync calendar');data.connections.calendarEvents=(payload.events||[]).map(e=>({...e,category:'Apple Calendar',connected:true}));data.connections.calendarLastSync=payload.updatedAt;saveData(false);refresh();showPage('calendar',false);if(!silent)toast('Apple Calendar synced.')}catch(error){if(!silent)toast(error.message||'Calendar sync failed.')}};
  window.disconnectCalendar=function(){data.connections.calendarUrl='';data.connections.calendarEvents=[];data.connections.calendarLastSync='';saveData(false);refresh();showPage('calendar',false);toast('Calendar disconnected.')};
  render(currentPage());const now=Date.now(),briefAge=now-Date.parse(data.liveBriefing.updatedAt||0),calAge=now-Date.parse(data.connections.calendarLastSync||0);if(!data.liveBriefing.topics?.length||briefAge>1800000)refreshMorningBrief(true);if(data.connections.calendarUrl&&calAge>900000)syncCalendar(true);
})();
