'use strict';
(function(){
  data.v10=data.v10||{live:{updatedAt:'',weather:null,markets:[],errors:[]},cloud:{status:'not-connected'},services:{gmail:'authorization-required',drive:'authorization-required',health:'bridge-required',calendar:'optional'}};
  const originalHome=window.homePage,originalSettings=window.settingsPage;
  const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
  const weatherText=code=>({0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Showers',82:'Heavy showers',95:'Thunderstorms'}[code]||'Current conditions');
  window.refreshV10Live=async function(silent=false){if(!silent)toast('Refreshing live dashboard…');try{const r=await fetch('/api/live',{headers:{accept:'application/json'}}),p=await r.json();if(!r.ok)throw new Error(p.error||'Live services unavailable');data.v10.live=p;saveData(false);refresh();if(!silent)toast('Live dashboard updated.')}catch(e){if(!silent)toast(e.message||'Live refresh failed.')}};
  function liveStrip(){const w=data.v10.live.weather?.current,m=data.v10.live.markets||[];return `<div class="v10-live-strip"><section><small>WEATHER • BALTIMORE</small><b>${w?`${fmt(w.temperature)}°F`:'Not synced'}</b><span>${w?`${weatherText(w.code)} • Feels ${fmt(w.feelsLike)}°`:'Tap refresh to connect'}</span></section>${m.slice(0,4).map(x=>`<section><small>${esc(x.symbol)}</small><b>${fmt(x.price)}</b><span class="${x.changePct>=0?'up':'down'}">${x.changePct>=0?'+':''}${fmt(x.changePct)}%</span></section>`).join('')}<button class="btn" onclick="refreshV10Live()">↻ Refresh Live</button></div>`}
  function connectionCard(name,status,detail,action,label){return `<section class="card v10-connection"><div><i class="${status}"></i><span><b>${name}</b><small>${detail}</small></span></div>${action?`<button class="btn" onclick="${action}">${label||'Open'}</button>`:''}</section>`}
  function connectionsPanel(){return `${section('Service Connections','What is live and what still requires authorization')}<div class="v10-connections">${connectionCard('Morning Brief',data.liveBriefing?.topics?.length?'connected':'ready',data.liveBriefing?.topics?.length?'Live headlines connected':'Ready to refresh','refreshMorningBrief()','Refresh')}${connectionCard('Career Jobs',data.v8?.jobs?.length?'connected':'ready',data.v8?.jobs?.length?`${data.v8.jobs.length} current matches`:'Ready to load','refreshCareerJobs()','Refresh')}${connectionCard('Weather & Markets',data.v10.live.updatedAt?'connected':'ready',data.v10.live.updatedAt?`Updated ${new Date(data.v10.live.updatedAt).toLocaleString()}`:'Ready to connect','refreshV10Live()','Refresh')}${connectionCard('Apple Calendar',data.connections?.calendarUrl?'connected':'optional',data.connections?.calendarUrl?'Published feed connected':'Published feed URL required',"showPage('calendar')",'Open')}${connectionCard('LinkedIn','connected','Walter Holleman profile linked',"window.open('https://www.linkedin.com/in/walter-holleman-19306027','_blank')",'Open')}${connectionCard('Gmail','required','Google OAuth credentials required for website access','','')}${connectionCard('Google Drive','required','Google OAuth credentials required for website access','','')}${connectionCard('Apple Health','required','Apple has no direct web API; requires Health Auto Export or a native bridge','','')}${connectionCard('Cloud Sync & Login','required','Supabase project URL and public key required','','')}</div>`}
  window.homePage=function(){return liveStrip()+originalHome()};
  window.settingsPage=function(){return connectionsPanel()+originalSettings()};
  const priorRender=window.render;
  window.render=function(active='home'){renders.home=homePage;renders.settings=settingsPage;priorRender(active);document.title='Holleman Command Center — V10'};
  render(currentPage());
  if(!data.v10.live.updatedAt||Date.now()-Date.parse(data.v10.live.updatedAt)>900000)refreshV10Live(true);
})();
