'use strict';
(function(){
  data.v11=data.v11||{};
  data.v11.workoutHistory=data.v11.workoutHistory||[];
  data.v11.workoutDraft=data.v11.workoutDraft||{name:'',date:today(),duration:'',notes:'',exercises:[{name:'',sets:'',reps:'',weight:''}]};
  const safe=u=>/^https:\/\//i.test(u||'')?u:'#';
  const sortedJobs=()=>[...(data.v8?.jobs||[])].filter(j=>safe(j.applyUrl)!=='#').sort((a,b)=>(b.fit||0)-(a.fit||0));
  function scheduledWorkout(dateStr=today()){
    if(dateStr==='2026-08-05')return data.workouts.find(w=>/pull/i.test(w.name))||data.workouts[0];
    const day=new Date(dateStr+'T12:00:00').getDay();
    const map={1:/push/i,2:/pull/i,3:/pull/i,4:/push/i,5:/pull/i,6:/ares|home/i,0:/recovery|mobility/i};
    return data.workouts.find(w=>map[day]?.test(w.name))||data.workouts[day%data.workouts.length]||data.workouts[0];
  }
  function parseExercise(line){const parts=String(line).split('—');return {name:(parts[0]||'').trim(),sets:'',reps:(parts[1]||'').trim(),weight:''}}
  window.startScheduledWorkout=function(){const w=scheduledWorkout();data.v11.workoutDraft={name:w?.name||'Workout',date:today(),duration:String(parseInt(w?.duration)||''),notes:'',exercises:(w?.exercises||[]).map(parseExercise)};data.v11.healthView='log';saveData(false);refresh();showPage('healthhub',false);toast('Today’s workout loaded.')};
  function jobsSection(){const jobs=sortedJobs().slice(0,6);return `<section class="home-career-opportunities"><div class="home-action-title"><h3>Live Career Opportunities</h3><span>${jobs.length} strong matches • refreshed every other day</span></div><div class="jobs">${jobs.map(j=>`<article class="home-job-card"><div class="head"><span class="tag">${esc(j.category||'Career')}</span><b>${j.fit||0}%</b></div><h4>${esc(j.title)}</h4><p>${esc(j.company)} • ${esc(j.location||'Location not listed')}</p><div class="meta"><span>${esc(j.salary||'Salary not listed')}</span><span>${esc(j.workModel||'Work model not listed')}</span></div><div class="actions"><a class="btn gold" href="${safe(j.applyUrl)}" target="_blank" rel="noopener">Open Job ↗</a><button class="btn" onclick="addLiveJobToPipeline(${(data.v8.jobs||[]).indexOf(j)})">Save</button></div></article>`).join('')||'<div class="empty">Refresh Career Jobs to load current opportunities.</div>'}</div></section>`}
  function trainingSection(){const w=scheduledWorkout(),ex=w?.exercises||[];return `<section class="card today-training"><div class="top"><div><div class="eyebrow">Today’s Training • ${new Date().toLocaleDateString(undefined,{month:'long',day:'numeric'})}</div><h2>${esc(w?.name||'Recovery Day')}</h2><p>${esc(w?.place||'Training')} • ${esc(w?.duration||'Flexible session')}</p></div><div class="fit">${ex.length}</div></div><div class="exercise-preview">${ex.slice(0,6).map(x=>{const p=parseExercise(x);return `<div><b>${esc(p.name)}</b><span>${esc(p.reps||'Planned exercise')}</span></div>`}).join('')}</div><div class="actions"><button class="btn gold" onclick="startScheduledWorkout()">Start & Log Workout</button><button class="btn" onclick="setHealthHub('log')">Open Workout Log</button><button class="btn" onclick="setHealthHub('strength')">View Strength Plan</button></div></section>`}
  const baseHome=window.homePage;
  window.homePage=function(){let html=baseHome();const marker='</div><div class="v11-row">';if(html.includes(marker))html=html.replace(marker,`</div>${jobsSection()}${trainingSection()}<div class="v11-row">`);else html=jobsSection()+trainingSection()+html;return html};
  window.addWorkoutExercise=function(){data.v11.workoutDraft.exercises.push({name:'',sets:'',reps:'',weight:''});saveData(false);refresh();showPage('healthhub',false)};
  window.updateWorkoutDraft=function(k,v){data.v11.workoutDraft[k]=v;saveData(false)};
  window.updateWorkoutExercise=function(i,k,v){data.v11.workoutDraft.exercises[i][k]=v;saveData(false)};
  window.removeWorkoutExercise=function(i){data.v11.workoutDraft.exercises.splice(i,1);if(!data.v11.workoutDraft.exercises.length)data.v11.workoutDraft.exercises.push({name:'',sets:'',reps:'',weight:''});saveData(false);refresh();showPage('healthhub',false)};
  window.saveWorkoutLog=function(){const d=data.v11.workoutDraft,ex=d.exercises.filter(x=>String(x.name||'').trim());if(!d.name&&!ex.length)return toast('Add a workout or exercise first.');data.v11.workoutHistory.unshift({id:Date.now(),name:d.name||'Workout',date:d.date||today(),duration:d.duration||'',notes:d.notes||'',exercises:clone(ex)});data.v11.workoutDraft={name:'',date:today(),duration:'',notes:'',exercises:[{name:'',sets:'',reps:'',weight:''}]};saveData(false);refresh();showPage('healthhub',false);toast('Workout saved.')};
  window.removeWorkoutLog=function(i){data.v11.workoutHistory.splice(i,1);saveData(false);refresh();showPage('healthhub',false)};
  function workoutLogPage(){const d=data.v11.workoutDraft,h=data.v11.workoutHistory,totalSets=d.exercises.reduce((n,x)=>n+(Number(x.sets)||0),0);return `${section('Workout Log','Track the session as you complete it')}<div class="workout-log-grid"><section class="card"><div class="card-title"><h3>Current Session</h3><div><button class="btn" onclick="startScheduledWorkout()">Load Today</button> <button class="btn" onclick="addWorkoutExercise()">＋ Exercise</button></div></div><div class="form"><label>Workout<input value="${esc(d.name)}" onchange="updateWorkoutDraft('name',this.value)"></label><label>Date<input type="date" value="${esc(d.date)}" onchange="updateWorkoutDraft('date',this.value)"></label><label>Duration<input type="number" value="${esc(d.duration)}" onchange="updateWorkoutDraft('duration',this.value)"></label><label>Notes<input value="${esc(d.notes)}" onchange="updateWorkoutDraft('notes',this.value)"></label></div><div class="workout-summary"><div><small>Exercises</small><b>${d.exercises.filter(x=>x.name).length}</b></div><div><small>Total Sets</small><b>${totalSets}</b></div><div><small>History</small><b>${h.length}</b></div></div>${d.exercises.map((x,i)=>`<div class="workout-exercise-row"><label>Exercise<input value="${esc(x.name)}" onchange="updateWorkoutExercise(${i},'name',this.value)"></label><label>Sets<input type="number" value="${esc(x.sets)}" onchange="updateWorkoutExercise(${i},'sets',this.value)"></label><label>Reps<input value="${esc(x.reps)}" onchange="updateWorkoutExercise(${i},'reps',this.value)"></label><label>Weight<input value="${esc(x.weight)}" onchange="updateWorkoutExercise(${i},'weight',this.value)"></label><button class="btn danger" onclick="removeWorkoutExercise(${i})">×</button></div>`).join('')}<button class="btn gold" style="margin-top:12px" onclick="saveWorkoutLog()">Finish & Save Workout</button></section><section class="card"><div class="card-title"><h3>Workout History</h3><span>${h.length} sessions</span></div>${h.map((w,i)=>`<div class="workout-history-item"><b>${esc(w.name)} • ${esc(w.date)}</b><span>${w.exercises.length} exercises${w.duration?` • ${esc(w.duration)} min`:''}</span><span>${w.exercises.map(x=>`${esc(x.name)} ${esc(x.sets)}×${esc(x.reps)} ${esc(x.weight)}`).join(' · ')}</span><button class="btn danger" style="margin-top:6px" onclick="removeWorkoutLog(${i})">Remove</button></div>`).join('')||'<div class="empty">No workouts logged yet.</div>'}</section></div>`}
  window.setHealthHub=function(v){data.v11.healthView=v;saveData(false);refresh();showPage('healthhub',false)};
  renders.healthhub=function(){const v=data.v11.healthView||'overview';const tab=`<div class="v11-hub-tabs">${[['overview','Recovery'],['log','Log Workout'],['running','Running'],['strength','Strength'],['nutrition','Nutrition'],['body','Body']].map(x=>`<button class="${v===x[0]?'active':''}" onclick="setHealthHub('${x[0]}')">${x[1]}</button>`).join('')}</div>`;const body=v==='log'?workoutLogPage():v==='running'?runningPage():v==='strength'?strengthPage():v==='nutrition'?nutritionPage():v==='body'?bodyPage():heartPage();return tab+body};
  renders.home=homePage;
  const priorRender=window.render;window.render=function(active='home'){renders.home=homePage;renders.healthhub=renders.healthhub;priorRender(active);document.title='Holleman Command Center — V11'};
  render(currentPage());
})();