'use strict';
(function(){
  data.v11=data.v11||{};
  data.v11.workoutDraft=data.v11.workoutDraft||{name:'',date:today(),duration:'',notes:'',exercises:[{name:'',sets:'',reps:'',weight:''}]};
  data.v11.workoutHistory=data.v11.workoutHistory||[];
  const safe=u=>/^https:\/\//i.test(u||'')?u:'#';
  const jobs=()=>[...(data.v8?.jobs||[])].sort((a,b)=>(b.fit||0)-(a.fit||0));
  function careerLinksBlock(){const list=jobs().slice(0,3);return `<div class="career-home-links">${list.map((j,i)=>`<div class="career-home-link"><div><b>${esc(j.title)}</b><span>${esc(j.company)} • ${esc(j.location||'')} • ${j.fit||0}% fit</span></div><div class="actions"><a class="btn gold" href="${safe(j.applyUrl)}" target="_blank" rel="noopener">Open Job ↗</a><button class="btn" onclick="addLiveJobToPipeline(${(data.v8.jobs||[]).indexOf(j)})">Save</button></div></div>`).join('')||'<div class="empty">Refresh Career Jobs to load live opportunities.</div>'}</div>`}
  const priorHome=window.homePage;
  window.homePage=function(){let html=priorHome();const careerStart=html.indexOf('<section class="card v11-career-hero">');if(careerStart<0)return html;const close=html.indexOf('</section>',careerStart);if(close<0)return html;const insertAt=close+10;html=html.slice(0,insertAt)+careerLinksBlock()+html.slice(insertAt);html=html.replace('<div class="v11-health-grid">','<div class="home-workout-shortcut"><div><b>Workout Log</b><span>Record exercises, sets, reps, weight, and notes as you train.</span></div><button class="btn gold" onclick="setHealthHub(\'log\')">Log Workout</button></div><div class="v11-health-grid">');return html};
  window.addWorkoutExercise=function(){data.v11.workoutDraft.exercises.push({name:'',sets:'',reps:'',weight:''});saveData(false);refresh();showPage('healthhub',false)};
  window.updateWorkoutDraft=function(key,value){data.v11.workoutDraft[key]=value;saveData(false)};
  window.updateWorkoutExercise=function(i,key,value){data.v11.workoutDraft.exercises[i][key]=value;saveData(false)};
  window.removeWorkoutExercise=function(i){data.v11.workoutDraft.exercises.splice(i,1);if(!data.v11.workoutDraft.exercises.length)data.v11.workoutDraft.exercises.push({name:'',sets:'',reps:'',weight:''});saveData(false);refresh();showPage('healthhub',false)};
  window.saveWorkoutLog=function(){const d=data.v11.workoutDraft;const exercises=d.exercises.filter(x=>String(x.name||'').trim());if(!String(d.name||'').trim()&&!exercises.length)return toast('Add a workout name or at least one exercise.');data.v11.workoutHistory.unshift({id:Date.now(),name:d.name||'Workout',date:d.date||today(),duration:d.duration||'',notes:d.notes||'',exercises:clone(exercises)});data.v11.workoutDraft={name:'',date:today(),duration:'',notes:'',exercises:[{name:'',sets:'',reps:'',weight:''}]};saveData(false);refresh();showPage('healthhub',false);toast('Workout logged.')};
  window.removeWorkoutLog=function(i){data.v11.workoutHistory.splice(i,1);saveData(false);refresh();showPage('healthhub',false);toast('Workout removed.')};
  function workoutLogPage(){const d=data.v11.workoutDraft,h=data.v11.workoutHistory;const totalSets=d.exercises.reduce((n,x)=>n+(Number(x.sets)||0),0),totalExercises=d.exercises.filter(x=>String(x.name||'').trim()).length;return `${section('Workout Log','Record the session as you complete it')}<div class="workout-log-grid"><section class="card"><div class="card-title"><h3>Current Session</h3><button class="btn" onclick="addWorkoutExercise()">＋ Exercise</button></div><div class="form"><label>Workout Name<input value="${esc(d.name)}" placeholder="Pull Day" onchange="updateWorkoutDraft('name',this.value)"></label><label>Date<input type="date" value="${esc(d.date)}" onchange="updateWorkoutDraft('date',this.value)"></label><label>Duration (minutes)<input type="number" min="0" value="${esc(d.duration)}" onchange="updateWorkoutDraft('duration',this.value)"></label><label>Notes<input value="${esc(d.notes)}" placeholder="Energy, pain, adjustments" onchange="updateWorkoutDraft('notes',this.value)"></label></div><div class="workout-summary"><div><small>Exercises</small><b>${totalExercises}</b></div><div><small>Total Sets</small><b>${totalSets}</b></div><div><small>Session</small><b>${esc(d.duration||'—')} min</b></div></div>${d.exercises.map((x,i)=>`<div class="workout-exercise-row"><label>Exercise<input value="${esc(x.name)}" placeholder="Arsenal High Row" onchange="updateWorkoutExercise(${i},'name',this.value)"></label><label>Sets<input type="number" min="0" value="${esc(x.sets)}" onchange="updateWorkoutExercise(${i},'sets',this.value)"></label><label>Reps<input value="${esc(x.reps)}" placeholder="8-12" onchange="updateWorkoutExercise(${i},'reps',this.value)"></label><label>Weight<input value="${esc(x.weight)}" placeholder="180 lb" onchange="updateWorkoutExercise(${i},'weight',this.value)"></label><button class="btn danger" onclick="removeWorkoutExercise(${i})">×</button></div>`).join('')}<button class="btn gold" style="margin-top:14px" onclick="saveWorkoutLog()">Save Workout</button></section><section class="card"><div class="card-title"><h3>Workout History</h3><span>${h.length} logged</span></div>${h.map((w,i)=>`<div class="workout-history-item"><b>${esc(w.name)} • ${esc(w.date)}</b><span>${w.exercises.length} exercises${w.duration?` • ${esc(w.duration)} min`:''}</span><span>${w.exercises.map(x=>`${esc(x.name)} ${esc(x.sets)}×${esc(x.reps)} ${esc(x.weight)}`).join(' · ')}</span><button class="btn danger" style="margin-top:7px" onclick="removeWorkoutLog(${i})">Remove</button></div>`).join('')||'<div class="empty">No workouts logged yet.</div>'}</section></div>`}
  const previousSetHealth=window.setHealthHub;
  window.setHealthHub=function(v){data.v11.healthView=v;saveData(false);refresh();showPage('healthhub',false)};
  const previousHealthHub=renders.healthhub;
  renders.healthhub=function(){const v=data.v11.healthView||'overview';const tabsHtml=`<div class="v11-hub-tabs">${[['overview','Recovery'],['log','Log Workout'],['running','Running'],['strength','Strength'],['nutrition','Nutrition'],['body','Body']].map(x=>`<button class="${v===x[0]?'active':''}" onclick="setHealthHub('${x[0]}')">${x[1]}</button>`).join('')}</div>`;if(v==='log')return tabsHtml+workoutLogPage();const body=v==='running'?runningPage():v==='strength'?strengthPage():v==='nutrition'?nutritionPage():v==='body'?bodyPage():heartPage();return tabsHtml+body};
  renders.home=homePage;
  const priorRender=window.render;
  window.render=function(active='home'){renders.home=homePage;renders.healthhub=renders.healthhub;priorRender(active);document.title='Holleman Command Center — V11'};
  render(currentPage());
})();