'use strict';
(function(){
  const safe=u=>/^https:\/\//i.test(u||'')?u:'#';
  const liveJobs=()=>[...(data.v8?.jobs||[])].sort((a,b)=>(b.fit||0)-(a.fit||0));
  const currentWorkout=()=>typeof getScheduledWorkout==='function'?getScheduledWorkout():null;
  const careerTasks=()=>{
    const tasks=[];
    (data.careerCommand?.pipeline||[]).filter(x=>x.next).slice(0,3).forEach(x=>tasks.push({label:x.next,sub:`${x.company||'Opportunity'} • ${x.role||''}`,priority:'High'}));
    (data.careerCommand?.priorities||[]).filter(x=>!x.done).slice(0,5-tasks.length).forEach(x=>tasks.push({label:x.title||x.label||'Career action',sub:x.note||'Career priority',priority:x.priority||'Medium'}));
    if(!tasks.length)tasks.push({label:'Review current opportunities',sub:'Career Command Center',priority:'Medium'});
    return tasks.slice(0,5);
  };
  function glance(){const w=data.v10?.weather,markets=data.v10?.markets||{},pipeline=data.careerCommand?.pipeline||[];return `<div class="v12-glance"><div><small>Readiness</small><b>${score()}%</b><em>${statusFor(score())}</em></div><div><small>Focus</small><b>${esc(data.briefing.focusMode)}</b><em>${esc(data.briefing.focus)}</em></div><div><small>Today</small><b>${upcoming().length} items</b><em>${upcoming()[0]?`Next ${toDisplayTime(upcoming()[0].start)}`:'Schedule clear'}</em></div><div><small>Weather</small><b>${w?.temperature!=null?Math.round(w.temperature)+'°':'—'}</b><em>${esc(w?.label||'Refresh needed')}</em></div><div><small>Markets</small><b>${esc(markets.dow?.change||markets.sp500?.change||'—')}</b><em>${esc(markets.dow?.price||markets.sp500?.price||'Live snapshot')}</em></div><div><small>Career Pipeline</small><b>${pipeline.length}</b><em>${pipeline.filter(x=>x.status==='Applied').length} applied • ${pipeline.filter(x=>/Interview/i.test(x.status||'')).length} interviewing</em></div></div>`}
  function briefCard(){const agenda=upcoming().slice(0,4),missions=[data.briefing.mission,...data.priorities.filter(x=>!x.done).slice(0,2).map(x=>x.title)];return `<section class="card"><div class="card-title"><h3>Morning Brief</h3><button class="btn" onclick="showPage('briefing')">View Full Brief</button></div><div class="v12-two" style="grid-template-columns:1fr 1fr"><div><small class="tag">TODAY'S MISSION</small><div class="v12-brief-list">${missions.filter(Boolean).map(x=>`<div class="v12-brief-item"><i>✓</i><b>${esc(x)}</b><span></span></div>`).join('')}</div></div><div><small class="tag">TODAY'S SCHEDULE</small><div class="v12-schedule-list">${agenda.map(e=>`<div class="v12-schedule-item"><i class="dot"></i><b>${esc(e.title)}</b><time>${esc(toDisplayTime(e.start))}</time></div>`).join('')||'<div class="empty">No events scheduled.</div>'}</div></div></div></section>`}
  function trainingCard(){const w=currentWorkout();if(!w)return `<section class="card v12-training"><div class="card-title"><h3>Today's Training</h3><span>No session scheduled</span></div><p class="copy">Open the workout log to record an unscheduled session.</p><button class="btn gold" onclick="setHealthHub('log')">Open Workout Log</button></section>`;const totalSets=w.exercises.reduce((n,x)=>{const m=x.match(/(\d+)\s*[×x]/);return n+(Number(m?.[1])||0)},0);return `<section class="card v12-training"><div class="card-title"><h3>Today's Training</h3><button class="btn" onclick="setHealthHub('strength')">View Plan</button></div><span class="tag">SCHEDULED</span><h2>${esc(w.name.replace('Arsenal ',''))} Day</h2><div class="v12-training-meta"><span>${esc(w.place)}</span><span>${esc(w.duration)}</span><span>${w.exercises.length} exercises</span></div><div class="v12-training-body"><div class="v12-training-summary"><div class="v12-progress-ring">0%</div><div class="v12-training-stats"><div><b>${w.exercises.length}</b><small>Exercises</small></div><div><b>${totalSets}</b><small>Sets</small></div><div><b>${parseInt(w.duration,10)||'—'}</b><small>Minutes</small></div></div><button class="btn gold" onclick="startScheduledWorkout()">▶ Start & Log Workout</button><button class="btn" onclick="setHealthHub('log')">Open Workout Log</button></div><div class="v12-exercise-table">${w.exercises.map((x,i)=>{const parts=x.split('—').map(s=>s.trim()),m=(parts[1]||'').match(/(\d+)\s*[×x]\s*(.+)/);return `<div class="v12-exercise"><span>${i+1}</span><b>${esc(parts[0])}</b><span>${esc(m?.[1]||'')}</span><span>${esc(m?.[2]||parts[1]||'')}</span></div>`}).join('')}</div></div></section>`}
  function healthCard(){const m=data.metrics;return `<section class="card"><div class="card-title"><h3>Health Snapshot</h3><button class="btn" onclick="showPage('healthhub')">View Health</button></div><div class="v12-health-list">${[['Recovery',score()+'%'],['Sleep',m.sleep.toFixed(1)+' h'],['Calories',m.calories.toLocaleString()],['Protein',m.protein+' g / '+m.proteinGoal+' g'],['Water',m.water+' oz / '+m.waterGoal+' oz']].map(x=>`<div class="v12-health-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><button class="btn" style="margin-top:10px" onclick="showPage('healthhub')">Log Nutrition / Measurements</button></section>`}
  function newsCard(){const topics=(data.liveBriefing?.topics||[]).slice(0,4);return `<section class="card"><div class="card-title"><h3>Morning Briefing</h3><button class="btn" onclick="showPage('briefing')">View All News</button></div>${topics.map(t=>{const s=t.stories?.[0];return `<div class="v12-news-item"><div>${s?.url?`<a href="${safe(s.url)}" target="_blank" rel="noopener">${esc(s.title||t.title||'Morning update')}</a>`:`<b>${esc(t.headline||t.title||'Morning update')}</b>`}<span>${esc(s?.source||t.title||'Briefing')}</span></div><span>${esc(s?.published||'')}</span></div>`}).join('')||'<div class="empty">Refresh Morning Brief to load current stories.</div>'}</section>`}
  function projectsCard(){return `<section class="card"><div class="card-title"><h3>Projects at a Glance</h3><button class="btn" onclick="showPage('projects')">View All Projects</button></div>${(data.v11?.projects||[]).slice(0,3).map(p=>`<div class="v12-project"><div class="v12-project-head"><div><b>${esc(p.type)} — ${esc(p.title)}</b><span>Due ${esc(p.due)}</span></div><b>${p.progress}%</b></div><div class="bar"><i style="width:${p.progress}%"></i></div></div>`).join('')||'<div class="empty">No projects yet.</div>'}</section>`}
  function careerCard(){const jobs=liveJobs().slice(0,6),tasks=careerTasks(),pipeline=data.careerCommand?.pipeline||[];return `<section class="card v12-career"><div class="card-title"><h3>Career Command Center</h3><button class="btn" onclick="showPage('career')">Go to Career Center</button></div><div class="v12-career-layout"><div class="v12-career-tasks"><small class="tag">TODAY'S CAREER ACTIONS</small>${tasks.map(t=>`<div class="v12-career-task"><input type="checkbox"><b>${esc(t.label)}</b><em>${esc(t.priority)}</em></div>`).join('')}<button class="btn" style="margin-top:10px" onclick="showPage('career')">View All Tasks</button></div><div><div class="card-title"><h3>Live Opportunities for You</h3><button class="btn" onclick="refreshCareerJobs()">↻ Refresh</button></div><div class="v12-job-carousel">${jobs.map(j=>`<article class="v12-job-card"><span class="tag">${esc(j.category||'Career')}</span><h4>${esc(j.title)}</h4><div class="company">${esc(j.company)}</div><div class="location">${esc(j.location||'')}</div><div class="salary">${esc(j.salary||'Compensation not listed')}</div><div class="fit">${j.fit||0}% Match</div><div class="v12-job-actions"><a class="btn gold" href="${safe(j.applyUrl)}" target="_blank" rel="noopener">Open Job</a><button class="btn" onclick="addLiveJobToPipeline(${(data.v8.jobs||[]).indexOf(j)})">Save</button></div><div class="why">Strong alignment with investigations, enterprise risk, security leadership, or regulated operations.</div></article>`).join('')||'<div class="empty">Refresh Career Jobs to load live opportunities.</div>'}</div></div></div><div class="v12-pipeline"><div><small>Saved</small><b>${pipeline.filter(x=>['Saved','Prospect','Interested'].includes(x.status)).length}</b></div><div><small>Applied</small><b>${pipeline.filter(x=>x.status==='Applied').length}</b></div><div><small>Interviewing</small><b>${pipeline.filter(x=>/Interview/i.test(x.status||'')).length}</b></div><div><small>Offers</small><b>${pipeline.filter(x=>/Offer/i.test(x.status||'')).length}</b></div><div><small>Last Updated</small><b>${data.v8?.jobsUpdatedAt?new Date(data.v8.jobsUpdatedAt).toLocaleString():'Waiting for refresh'}</b></div></div></section>`}
  function quickBar(){return `<div class="v12-quickbar"><button class="btn gold" onclick="startScheduledWorkout()">＋ Log Workout</button><button class="btn" onclick="showPage('nutrition')">Log Food</button><button class="btn" onclick="showPage('projects')">Add Task</button><button class="btn" onclick="showPage('calendar')">Add Event</button><button class="btn" onclick="showPage('settings')">Connections</button></div>`}
  function homeV12(){return `<div class="v12-home">${glance()}<div class="v12-two">${briefCard()}${trainingCard()}</div><div class="v12-three">${healthCard()}${newsCard()}${projectsCard()}</div>${careerCard()}${quickBar()}</div>`}
  renders.home=homeV12;
  const previousRender=window.render;
  window.render=function(active='home'){renders.home=homeV12;previousRender(active);document.title='Holleman Command Center — V12 Beta'};
  render('home');
})();