'use strict';
(function(){
  const baseCareerPage=window.careerPage;
  const stages=['Prospect','Saved','Applied','Recruiter Screen','Hiring Manager','Interview','Final Round','Offer','Closed'];
  const priorities=['High','Medium','Low'];
  const defaultsV7={
    targetRoles:[
      {title:'Director, Corporate Investigations',fit:94,range:'$175k–$225k',mode:'Remote / Hybrid',keywords:'investigations, intelligence, fraud, ethics'},
      {title:'Director, Enterprise Risk',fit:91,range:'$170k–$220k',mode:'Hybrid',keywords:'risk, controls, governance, banking'},
      {title:'Director, Global Security Operations',fit:89,range:'$175k–$230k',mode:'Hybrid / Remote',keywords:'security operations, crisis, investigations'},
      {title:'Senior Program Director, Crisis Management',fit:87,range:'$165k–$215k',mode:'Remote / Hybrid',keywords:'command center, continuity, escalation'},
      {title:'Head of Investigations / Intelligence',fit:92,range:'$180k–$240k',mode:'Remote / Hybrid',keywords:'intelligence, investigations, executive reporting'}
    ],
    network:[
      {name:'',organization:'',role:'Recruiter',status:'To Contact',lastContact:'',nextAction:'',email:'',linkedin:''}
    ],
    skills:[
      {name:'Executive resume',category:'Positioning',status:'In Progress',priority:'High'},
      {name:'LinkedIn executive brand',category:'Positioning',status:'Not Started',priority:'High'},
      {name:'Security+ certification',category:'Credential',status:'Considering',priority:'Medium'},
      {name:'Corporate investigations terminology',category:'Knowledge',status:'In Progress',priority:'High'},
      {name:'Executive interview stories',category:'Interview',status:'In Progress',priority:'High'}
    ],
    achievements:[
      {title:'Complex investigations',detail:'Lead multi-target narcotics investigations and coordinate local and federal partners toward state and federal action.',category:'Law Enforcement'},
      {title:'Multi-state team leadership',detail:'Built and managed a 50-person team deployed across more than 120 banking locations.',category:'Banking Leadership'},
      {title:'Risk and performance management',detail:'Managed expenses, mileage, staffing, retention, and performance across a large distributed operation.',category:'Operations'},
      {title:'Cross-functional coordination',detail:'Translate intelligence, evidence, operational constraints, and timelines into clear actions for multiple stakeholders.',category:'Leadership'}
    ],
    stories:[
      {title:'Leading through ambiguity',situation:'Complex investigation with multiple targets and partner agencies.',action:'Established priorities, coordinated resources, and maintained evidence and timeline discipline.',result:'Moved the investigation toward actionable state or federal outcomes.'},
      {title:'Building a distributed team',situation:'Needed to create and deploy a large multi-state banking team.',action:'Recruited, hired, retained, scheduled, coached, and managed expenses and performance.',result:'Built a functioning 50-person operation supporting 120+ branches.'}
    ],
    weekly:{applicationsGoal:5,networkGoal:5,followupsGoal:5},
    activeView:'overview'
  };
  data.careerV7=deepMerge(clone(defaultsV7),data.careerV7||{});
  const c7=()=>data.careerV7;
  const clean=(v='')=>String(v||'').trim();
  const opportunityCount=()=>data.careerCommand?.pipeline?.length||0;
  const stageCount=s=>(data.careerCommand?.pipeline||[]).filter(x=>x.status===s).length;
  const nextActions=()=>[
    ...(data.careerCommand?.pipeline||[]).filter(x=>clean(x.next)).map(x=>({label:x.next,sub:`${x.company||'Opportunity'} • ${x.role||'Role'}`,type:'Opportunity'})),
    ...c7().network.filter(x=>clean(x.nextAction)).map(x=>({label:x.nextAction,sub:`${x.name||'Contact'} • ${x.organization||'Network'}`,type:'Networking'})),
    ...(data.careerCommand?.priorities||[]).filter(x=>!x.done).map(x=>({label:x.title,sub:'Weekly priority',type:'Priority'}))
  ].slice(0,6);
  function careerTabs(active){return `<div class="career-tabs">${[['overview','Overview'],['pipeline','Job Pipeline'],['network','Networking'],['materials','Materials'],['skills','Skills'],['stories','Interview Prep']].map(x=>`<button class="${active===x[0]?'active':''}" onclick="setCareerView('${x[0]}')">${x[1]}</button>`).join('')}</div>`}
  window.setCareerView=function(view){data.careerV7.activeView=view;saveData(false);renders.career=careerPage;refresh();showPage('career',false)};
  window.addNetworkContact=function(){c7().network.unshift({name:'',organization:'',role:'Recruiter',status:'To Contact',lastContact:'',nextAction:'',email:'',linkedin:''});saveData(false);refresh();showPage('career',false)};
  window.updateNetwork=function(i,key,value){c7().network[i][key]=value;saveData(false)};
  window.removeNetwork=function(i){c7().network.splice(i,1);saveData(false);refresh();showPage('career',false)};
  window.addSkill=function(){c7().skills.unshift({name:'',category:'Knowledge',status:'Not Started',priority:'Medium'});saveData(false);refresh();showPage('career',false)};
  window.updateSkill=function(i,key,value){c7().skills[i][key]=value;saveData(false)};
  window.removeSkill=function(i){c7().skills.splice(i,1);saveData(false);refresh();showPage('career',false)};
  window.addStory=function(){c7().stories.unshift({title:'',situation:'',action:'',result:''});saveData(false);refresh();showPage('career',false)};
  window.updateStory=function(i,key,value){c7().stories[i][key]=value;saveData(false)};
  window.removeStory=function(i){c7().stories.splice(i,1);saveData(false);refresh();showPage('career',false)};
  window.addAchievement=function(){c7().achievements.unshift({title:'',detail:'',category:'Leadership'});saveData(false);refresh();showPage('career',false)};
  window.updateAchievement=function(i,key,value){c7().achievements[i][key]=value;saveData(false)};
  window.removeAchievement=function(i){c7().achievements.splice(i,1);saveData(false);refresh();showPage('career',false)};
  function overviewView(){
    const c=data.careerCommand, actions=nextActions(), readiness=careerScore();
    return `<div class="career-hero-grid"><section class="card career-hero"><div><div class="eyebrow">Career Command Center • V7</div><h2>Move from public service into senior private-sector leadership.</h2><p>${esc(c.profile)}</p><div class="career-targets"><span><small>COMPENSATION</small><b>$175k–$200k+</b></span><span><small>STRETCH</small><b>$225k+</b></span><span><small>TRANSITION</small><b>3–6 months</b></span><span><small>MODEL</small><b>Remote / Hybrid</b></span></div></div><div class="career-score"><small>TRANSITION READINESS</small><strong>${readiness}</strong><span>${readiness>=75?'Strong foundation':readiness>=50?'Building momentum':'Foundation phase'}</span></div></section><section class="card"><div class="card-title"><h3>Next Best Actions</h3><span>${actions.length} queued</span></div><div class="career-actions">${actions.map(a=>`<div><i></i><span><b>${esc(a.label)}</b><small>${esc(a.sub)}</small></span><em>${a.type}</em></div>`).join('')||'<div class="empty">Add opportunities or networking follow-ups to build the queue.</div>'}</div></section></div>
    <div class="career-kpis"><section><small>OPPORTUNITIES</small><b>${opportunityCount()}</b><span>${stageCount('Applied')} applied</span></section><section><small>INTERVIEW STAGES</small><b>${stageCount('Interview')+stageCount('Final Round')+stageCount('Hiring Manager')}</b><span>Active conversations</span></section><section><small>NETWORK</small><b>${c7().network.filter(x=>clean(x.name)).length}</b><span>${c7().network.filter(x=>x.status==='Follow Up').length} follow-ups</span></section><section><small>MATERIALS READY</small><b>${Object.values(c.documents).filter(x=>x==='Ready').length}/${Object.keys(c.documents).length}</b><span>Resume, LinkedIn, stories</span></section><section><small>WEEKLY APPLICATIONS</small><b>${c.applications}/${c7().weekly.applicationsGoal}</b><span>Quality targets</span></section></div>
    ${section('Target Role Map','Best-fit leadership lanes')}<div class="target-role-grid">${c7().targetRoles.map(r=>`<section class="card target-role"><div class="fit-ring" style="--fit:${r.fit}"><span>${r.fit}%</span></div><div><h3>${esc(r.title)}</h3><p>${esc(r.range)} • ${esc(r.mode)}</p><small>${esc(r.keywords)}</small></div></section>`).join('')}</div>
    ${section('Career Narrative','Your strongest proof points')}<div class="achievement-grid">${c7().achievements.slice(0,4).map(a=>`<section class="card achievement"><span>${esc(a.category)}</span><h3>${esc(a.title)}</h3><p>${esc(a.detail)}</p></section>`).join('')}</div>
    ${section('90-Day Transition','Positioning, market activity, and conversion')}<div class="roadmap"><section class="card"><b>01</b><h3>Positioning</h3><p>Finalize executive resume, LinkedIn profile, target-role language, and leadership stories.</p></section><section class="card"><b>02</b><h3>Market Activity</h3><p>Build a targeted company list, apply selectively, and create consistent recruiter and hiring-leader outreach.</p></section><section class="card"><b>03</b><h3>Conversion</h3><p>Prepare executive interviews, evaluate fit and compensation, and negotiate around flexibility and long-term growth.</p></section></div>`
  }
  function pipelineView(){
    const rows=data.careerCommand.pipeline||[];
    return `<div class="career-toolbar"><div><h2>Job Pipeline</h2><p>Track every target from first look through offer.</p></div><button class="btn gold" onclick="addCareerOpportunity()">＋ Add Opportunity</button></div><div class="pipeline-summary">${stages.map(s=>`<div><b>${stageCount(s)}</b><span>${s}</span></div>`).join('')}</div><section class="card career-table-wrap"><div class="career-table">${rows.length?rows.map((j,i)=>`<article class="opportunity-row"><div class="opp-main"><input class="opp-company" placeholder="Company" value="${esc(j.company||'')}" onchange="updateCareerOpportunity(${i},'company',this.value)"><input class="opp-role" placeholder="Role" value="${esc(j.role||'')}" onchange="updateCareerOpportunity(${i},'role',this.value)"></div><label>Stage<select onchange="updateCareerOpportunity(${i},'status',this.value)">${stages.map(x=>`<option ${j.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Compensation<input placeholder="$175k–$225k" value="${esc(j.salary||'')}" onchange="updateCareerOpportunity(${i},'salary',this.value)"></label><label>Next Action<input placeholder="Follow up Friday" value="${esc(j.next||'')}" onchange="updateCareerOpportunity(${i},'next',this.value)"></label><label>Link<input placeholder="https://" value="${esc(j.link||'')}" onchange="updateCareerOpportunity(${i},'link',this.value)"></label><button class="btn danger" onclick="removeCareerOpportunity(${i})">×</button></article>`).join(''):'<div class="empty">No opportunities yet. Add the first role you want to track.</div>'}</div></section>`
  }
  function networkView(){return `<div class="career-toolbar"><div><h2>Networking</h2><p>Manage recruiters, hiring leaders, referrals, and follow-ups.</p></div><button class="btn gold" onclick="addNetworkContact()">＋ Add Contact</button></div><div class="network-grid">${c7().network.map((n,i)=>`<section class="card network-card"><div class="card-title"><h3>${esc(n.name||'New Contact')}</h3><button class="btn danger" onclick="removeNetwork(${i})">×</button></div><div class="form"><label>Name<input value="${esc(n.name)}" onchange="updateNetwork(${i},'name',this.value)"></label><label>Organization<input value="${esc(n.organization)}" onchange="updateNetwork(${i},'organization',this.value)"></label><label>Relationship<select onchange="updateNetwork(${i},'role',this.value)">${['Recruiter','Hiring Leader','Referral','Former Colleague','Industry Contact'].map(x=>`<option ${n.role===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Status<select onchange="updateNetwork(${i},'status',this.value)">${['To Contact','Contacted','Follow Up','Meeting Set','Active Relationship'].map(x=>`<option ${n.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Last Contact<input type="date" value="${esc(n.lastContact)}" onchange="updateNetwork(${i},'lastContact',this.value)"></label><label>Next Action<input value="${esc(n.nextAction)}" onchange="updateNetwork(${i},'nextAction',this.value)"></label><label>Email<input type="email" value="${esc(n.email)}" onchange="updateNetwork(${i},'email',this.value)"></label><label>LinkedIn<input value="${esc(n.linkedin)}" onchange="updateNetwork(${i},'linkedin',this.value)"></label></div></section>`).join('')}</div>`}
  function materialsView(){const c=data.careerCommand;return `<div class="career-toolbar"><div><h2>Career Materials</h2><p>Keep the core assets ready for targeted opportunities.</p></div></div><div class="material-grid">${Object.entries(c.documents).map(([k,v])=>`<section class="card material-card"><small>${esc(k.replace(/([A-Z])/g,' $1'))}</small><h3>${esc(v)}</h3><select onchange="updateCareerDocument('${k}',this.value)"><option ${v==='Not Started'?'selected':''}>Not Started</option><option ${v==='In Progress'?'selected':''}>In Progress</option><option ${v==='Ready'?'selected':''}>Ready</option></select><div class="material-progress"><i style="width:${v==='Ready'?100:v==='In Progress'?55:8}%"></i></div></section>`).join('')}</div>${section('Achievement Bank','Resume bullets, LinkedIn proof points, and interview evidence')}<div class="achievement-editor"><button class="btn gold" onclick="addAchievement()">＋ Add Achievement</button>${c7().achievements.map((a,i)=>`<section class="card"><div class="form"><label>Title<input value="${esc(a.title)}" onchange="updateAchievement(${i},'title',this.value)"></label><label>Category<input value="${esc(a.category)}" onchange="updateAchievement(${i},'category',this.value)"></label><label class="span2">Business Value<textarea onchange="updateAchievement(${i},'detail',this.value)">${esc(a.detail)}</textarea></label></div><button class="btn danger" onclick="removeAchievement(${i})">Remove</button></section>`).join('')}</div>`}
  function skillsView(){return `<div class="career-toolbar"><div><h2>Skills & Credentials</h2><p>Close only the gaps that improve access to target roles.</p></div><button class="btn gold" onclick="addSkill()">＋ Add Skill</button></div><div class="skills-table">${c7().skills.map((s,i)=>`<section class="card skill-row"><input placeholder="Skill or credential" value="${esc(s.name)}" onchange="updateSkill(${i},'name',this.value)"><select onchange="updateSkill(${i},'category',this.value)">${['Positioning','Credential','Knowledge','Interview','Technology'].map(x=>`<option ${s.category===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="updateSkill(${i},'status',this.value)">${['Not Started','Considering','In Progress','Completed'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="updateSkill(${i},'priority',this.value)">${priorities.map(x=>`<option ${s.priority===x?'selected':''}>${x}</option>`).join('')}</select><button class="btn danger" onclick="removeSkill(${i})">×</button></section>`).join('')}</div>`}
  function storiesView(){return `<div class="career-toolbar"><div><h2>Interview Story Bank</h2><p>Translate your experience into concise executive examples.</p></div><button class="btn gold" onclick="addStory()">＋ Add Story</button></div><div class="story-grid">${c7().stories.map((s,i)=>`<section class="card story-card"><div class="card-title"><h3>${esc(s.title||'New Story')}</h3><button class="btn danger" onclick="removeStory(${i})">×</button></div><label>Story Title<input value="${esc(s.title)}" onchange="updateStory(${i},'title',this.value)"></label><label>Situation<textarea onchange="updateStory(${i},'situation',this.value)">${esc(s.situation)}</textarea></label><label>Action<textarea onchange="updateStory(${i},'action',this.value)">${esc(s.action)}</textarea></label><label>Result<textarea onchange="updateStory(${i},'result',this.value)">${esc(s.result)}</textarea></label></section>`).join('')}</div>`}
  window.careerPage=function(){const view=c7().activeView||'overview';const body={overview:overviewView,pipeline:pipelineView,network:networkView,materials:materialsView,skills:skillsView,stories:storiesView}[view]();return careerTabs(view)+body};
  function topBriefStories(){const topics=data.liveBriefing?.topics||[];return topics.slice(0,4).map(t=>{const item=t.items?.[0];return item?`<a class="v7-story" href="${item.link}" target="_blank" rel="noopener"><span>${esc(t.title)}</span><b>${esc(item.title)}</b><small>${esc(item.source||'News')}</small></a>`:''}).join('')}
  window.homePage=function(){const m=data.metrics,r=score(),events=upcoming().slice(0,4),actions=nextActions().slice(0,4),pending=data.priorities.filter(x=>!x.done);return `<div class="v7-home-hero"><section class="card v7-brief-hero"><div><div class="eyebrow">Morning Brief</div><h2>${esc(data.briefing.headline)}</h2><p>${esc(data.briefing.summary)}</p><div class="v7-hero-meta"><span><small>MISSION</small><b>${esc(data.briefing.mission)}</b></span><span><small>FOCUS MODE</small><b>${esc(data.briefing.focusMode)}</b></span><span><small>READINESS</small><b>${r} • ${statusFor(r)}</b></span></div></div><div class="v7-date-block"><small>TODAY</small><b>${new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})}</b><span>${new Date().toLocaleDateString(undefined,{weekday:'long'})}</span></div></section><section class="card v7-today-card"><div class="card-title"><h3>Today's Schedule</h3><span onclick="showPage('calendar')">Open Calendar</span></div>${events.map(e=>`<div class="v7-agenda"><time>${esc(toDisplayTime(e.start))}</time><div><b>${esc(e.title)}</b><small>${esc(e.category||'General')}</small></div></div>`).join('')||'<div class="empty">No events scheduled.</div>'}</section></div>
  <div class="v7-snapshot-row"><button onclick="showPage('command')"><small>OPEN PRIORITIES</small><b>${pending.length}</b><span>${pending[0]?esc(pending[0].title):'All complete'}</span></button><button onclick="showPage('heart')"><small>SLEEP</small><b>${m.sleep.toFixed(1)}h</b><span>HRV ${m.hrv} ms</span></button><button onclick="showPage('nutrition')"><small>NUTRITION</small><b>${m.protein}g</b><span>Protein • ${m.water} oz water</span></button><button onclick="showPage('career')"><small>CAREER</small><b>${opportunityCount()}</b><span>${actions[0]?esc(actions[0].label):'Build pipeline'}</span></button></div>
  <div class="v7-home-grid"><section class="card"><div class="card-title"><h3>Command Priorities</h3><span>${pending.length} open</span></div>${data.priorities.slice(0,5).map((p,i)=>`<div class="mission ${p.done?'done':''}"><input type="checkbox" ${p.done?'checked':''} onchange="togglePriority(${i},this.checked)"><label>${esc(p.title)}</label><small>${esc(p.time)}</small></div>`).join('')}</section><section class="card"><div class="card-title"><h3>Career Next Actions</h3><span onclick="showPage('career')">Career Center</span></div><div class="career-actions compact">${actions.map(a=>`<div><i></i><span><b>${esc(a.label)}</b><small>${esc(a.sub)}</small></span></div>`).join('')||'<div class="empty">No career actions queued.</div>'}</div></section></div>
  ${section('Morning Brief','Top stories across your briefing categories')}<div class="v7-story-grid">${topBriefStories()||'<section class="card"><p class="copy">Refresh Morning Brief to load current headlines.</p><button class="btn gold" onclick="refreshMorningBrief()">Refresh</button></section>'}</div>
  ${section('Daily Metrics','Only the numbers that shape today')}<div class="grid six">${metric('Readiness',r+'%',statusFor(r),r,true)}${metric('Resting HR',m.restingHr+' bpm','Current',80)}${metric('HRV',m.hrv+' ms','Recovery',m.hrv)}${metric('Sleep',m.sleep.toFixed(1)+' h','Last night',m.sleep/8*100)}${metric('Protein',m.protein+' g','Daily target',m.protein/m.proteinGoal*100)}${metric('Weight',m.weight.toFixed(1)+' lb','Goal '+m.goalWeight,m.goalWeight/m.weight*100,true)}</div>`};
  renders.home=window.homePage;renders.career=window.careerPage;
  tabs.forEach(t=>{if(t[0]==='career'){t[1]='Career Center';t[3]='Career Command Center'}if(t[0]==='home'){t[3]='Morning Brief'}});
  render(currentPage());
})();
